<?php
/**
 * Functions related to the display of the site icon.
 *
 * @author  Marco Di Bella <mdb@marcodibella.de>
 * @package mdb-theme-fse
 */


/** Prevent direct access */

defined( 'ABSPATH' ) or exit;



/**
 * Adds the favicon.
 *
 * @since  1.8.0
 * @param  array $meta_tags    The meta tags generated by WordPress.
 * @return array               The modified meta tags.
 */

function mdb_site_icon_meta_tags( $meta_tags )
{
    $icon_svg = get_template_directory_uri() . '/assets/build/img/marco-logo.svg';
    $icon_512 = get_template_directory_uri() . '/assets/build/img/marco-logo-512.png';
    $icon_192 = get_template_directory_uri() . '/assets/build/img/marco-logo-192.png';

    $meta_tags   = array();
    $meta_tags[] = sprintf( '<link rel="icon" href="%s">', esc_url( $icon_512 ) );
    $meta_tags[] = sprintf( '<link rel="shortcut icon" href="%s">', esc_url( $icon_svg ) );
    $meta_tags[] = sprintf( '<link rel="apple-touch-icon" href="%s">', esc_url( $icon_192 ) );
    $meta_tags[] = sprintf( '<meta name="msapplication-TileImage" content="%s">', esc_url( $icon_192 ) );

    return $meta_tags;
}

add_filter( 'site_icon_meta_tags', 'mdb_site_icon_meta_tags' );



/**
 * Sends correct "favicon.ico" redirect.
 *
 * @since 1.8.0
 * @see   https://make.wordpress.org/core/2020/02/19/enhancements-to-favicon-handling-in-wordpress-5-4/
 */

function mdb_do_faviconico()
{
    $icon_svg = get_template_directory_uri() . '/assets/build/img/marco-logo.svg';

    wp_redirect( $icon_svg );
 	exit;
}

add_action( 'do_faviconico', 'mdb_do_faviconico' );
